version: "3"

services:
  mongodb:
    image: mongo:4.4.6
    container_name: "MongoDB"
    ports:
      - "27017:27017"
  website:
    build: .
    container_name: "Webserver_Flask"
    stop_signal: SIGINT
    volumes:
      - "./webserver:/webserver"
    ports:
      - "5001:5001"
    depends_on:
      - mongodb
